### ISSUE TITLE
Gerowallet not working[BUG] 

### ISSUE THREAD

**Issue by coding-circulate** [cardano-foundation/cardano-connect-with-wallet#15]
**Describe :** 
 Whenever i click on connect button it redirect me on install extension page of gero wallet.

This is the code im running .
<ConnectWalletButton
        alwaysVisibleWallets={["gerowallet", "typhon", "flint", "nufi"]}
      />`
`

**Comment by fabianbormann** [comment]
Can you please test if the error will go away if you add gerowallet to the "supportedWallets" prop ? 

`<ConnectWalletButton
supportedWallets={[["gerowallet", "typhon", "flint", "nufi"]]}
alwaysVisibleWallets={["gerowallet"]}
/>`

**Comment by coding-circulate** [comment]
No it still not working . redirect me on a Gerowallet extension page

**Comment by fabianbormann** [comment]
Ok I figured it out: gerowallet does not inject it's api to the window.cardano object on localhost nor on unsecure sites (invalid cert). If you deploy your site to production gerowallet will be shown up. You can test this by going to any https site, open the devtools and check "window.cardano.gerowallet" .. on localhost this will be undefined. I will close this issue here and suggest you to contact the gerowallet developers (maybe there is a dev/test mode).

**Comment by coding-circulate** [comment]
yes its working now thank you so much. 

**_Just for Public_**
Run your react app by this command   **set HTTPS=true&&npm start**  and Gerowallet will work
