### ISSUE TITLE
[BUG] Can not write unit test if i import this library. I use jest, testing-library and styled-components

### ISSUE THREAD

**Issue by hhtrung55** [cardano-foundation/cardano-connect-with-wallet#53]
![image](https://github.com/cardano-foundation/cardano-connect-with-wallet/assets/48503033/30f572c1-6aa1-44cd-bd8e-94684fa37e11)

**Comment by VuCoKhoi** [comment]
I have the same problem!!!

**Comment by cfuisat** [comment]
Hi, 
you need to create a .d.ts file in your project root folder where package.json file exists, 
example: global.d.ts and include the below line
// global.d.ts
`declare module "@cardano-foundation/cardano-connect-with-wallet"`

Also, you should also be listed as a part of your project in your tsconfig.json
`  "include": [
    "**/*.ts",
    "**/*.tsx",
    "global.d.ts"
  ],`

See if it fix the issue.

**Comment by fabianbormann** [comment]
We will look into this. Thanks for opening the issue.

**Comment by fabianbormann** [comment]
We use cypress for testing maybe your jest tests are matching to that .test files name pattern and this causes the error. I wiill check if it's possible to change our name pattern to not confuse your test setup

**Comment by fabianbormann** [comment]
@cfuisat your issue has been fixed by the latest release 0.1.57. It was just a wrong path to the type declarations :) .. But I think the issue of @hhtrung55  and @VuCoKhoi is regarding to this https://github.com/cypress-io/cypress/issues/22059 . @hhtrung55 I have no jest running. Can you please try this solution and tell me if it works? https://github.com/cypress-io/cypress/issues/22059#issuecomment-1148921141 A PR would be great 👍
